-- MySQL Script generated by MySQL Workbench
-- Mon Jul 17 17:57:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dev_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dev_db` ;

-- -----------------------------------------------------
-- Schema dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev_db` DEFAULT CHARACTER SET utf8 ;
USE `dev_db` ;

-- -----------------------------------------------------
-- Table `dev_db`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`skills` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`skills` (
  `skills_id` INT(11) NOT NULL AUTO_INCREMENT,
  `skills_name` VARCHAR(45) NULL,
  PRIMARY KEY (`skills_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`companies` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`companies` (
  `company_id` INT(11) NOT NULL,
  `company_name` VARCHAR(45) NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`developers` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`developers` (
  `developers_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `age` INT(11) NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`developers_id`, `company_id`),
  INDEX `fk_developers_companies_idx` (`company_id` ASC),
  CONSTRAINT `fk_developers_companies`
    FOREIGN KEY (`company_id`)
    REFERENCES `dev_db`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`developers_has_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`developers_has_skills` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`developers_has_skills` (
  `skills_id` INT(11) NOT NULL,
  `developers_id` INT(11) NOT NULL,
  INDEX `fk_developers_has_skills_developers_idx_idx` (`developers_id` ASC),
  PRIMARY KEY (`skills_id`, `developers_id`),
  CONSTRAINT `fk_developers_has_skills_skills`
    FOREIGN KEY (`skills_id`)
    REFERENCES `dev_db`.`skills` (`skills_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_developers`
    FOREIGN KEY (`developers_id`)
    REFERENCES `dev_db`.`developers` (`developers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`projects` (
  `projects_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NULL,
  `company_id` INT(11) NOT NULL,
  PRIMARY KEY (`projects_id`, `company_id`),
  INDEX `fk_projects_companies_idx` (`company_id` ASC),
  CONSTRAINT `fk_projects_companies`
    FOREIGN KEY (`company_id`)
    REFERENCES `dev_db`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`projects_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`projects_has_developers` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`projects_has_developers` (
  `projects_id` INT NOT NULL,
  `developers_id` INT(11) NOT NULL,
  PRIMARY KEY (`projects_id`, `developers_id`),
  INDEX `fk_projects_has_developers_developers_idx` (`developers_id` ASC),
  CONSTRAINT `fk_projects_has_developers_projects`
    FOREIGN KEY (`projects_id`)
    REFERENCES `dev_db`.`projects` (`projects_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_developers_developers`
    FOREIGN KEY (`developers_id`)
    REFERENCES `dev_db`.`developers` (`developers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`customers` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`customers` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `projects_id`),
  INDEX `fk_customers_projects_idx` (`projects_id` ASC),
  CONSTRAINT `fk_customers_projects`
    FOREIGN KEY (`projects_id`)
    REFERENCES `dev_db`.`projects` (`projects_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
